#Jaisen McLean
import hashlib

from Crypto.Hash import SHA256

# Plaintext password of target_hash is pass123
target_hash= "9b8769a4a742959a2d0298c36fb70623f2dfacda8436237df08d8dfd5b37374c"

def get_user_pass():
    """
    This function takes user input adn returns that password
    :return:
    """
    print("You will be prompted to enter your password. Please enter the correct password for access\n")
    user_pass= input("Please enter the password now: ")
    return user_pass


def get_sha256(user_pass):
    """
    This function takes the user password and hashes the password
    :param user_pass:
    :return:
    """
    user_hash = user_pass.encode('utf-8')
    user_hash = hashlib.sha256(user_hash).hexdigest()
    print("Your SHA256 hash is:")
    return user_hash


def compare_hashes(user_hash, target_hash):
    """
    this function compares the hashes generated by get_sha256
    :param user_hash:
    :param target_hash:
    :return:
    """
    if user_hash == target_hash:
        print("Your password is correct")
    else:
        print("Your password is incorrect")

user_pass= get_user_pass()
user_hash= get_sha256(user_pass)
compare_hashes(user_hash, target_hash)



